databases:
  - name: "Database_1"
    description: "(Ln,Phi,Ai,lx,ly,lz,Lz,tc,Ts,As,Zs)"
    base_scenario: "CycloneBaseCase"

    varying_parameters:
      - name: "Ln"
        mode: "linspace"
        min: 0.0
        max: 10.0
        nvals: 21

      - name: "Phi"
        mode: "linspace"
        min: 0.0
        max: 0.06
        nvals: 21

      - name: "Ai"
        mode: "linspace"
        min: 0.0
        max: 1.0
        nvals: 21

      - name: "lambdax"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambday"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambdaz"
        mode: "linspace"
        min: 0.5
        max: 5.0
        nvals: 21

      - name: "lbalonz"
        mode: "linspace"
        min: 0.5
        max: 5.0
        nvals: 21

      - name: "tauc"
        mode: "linspace"
        min: 0.5
        max: 10.0
        nvals: 21

      - name: "Ts"
        mode: "linspace"
        min: 0.1
        max: 4.1
        nvals: 21

      - name: "As"
        mode: "linspace"
        min: 1.0
        max: 5.0
        nvals: 21

      - name: "Zs"
        mode: "linspace"
        min: 0.1
        max: 5.1
        nvals: 21

# # # # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  - name: "Database_2"
    description: "(Ln,Phi,Ai,lx,ly,lz,Lz,tc,Ts,As)"
    base_scenario: "CycloneBaseCase"

    varying_parameters:
      - name: "Ln"
        mode: "linspace"
        min: 0.0
        max: 10.0
        nvals: 21

      - name: "Phi"
        mode: "linspace"
        min: 0.0
        max: 0.06
        nvals: 21

      - name: "Ai"
        mode: "linspace"
        min: 0.0
        max: 1.0
        nvals: 21

      - name: "lambdax"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambday"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambdaz"
        mode: "linspace"
        min: 0.5
        max: 5.0
        nvals: 21

      - name: "lbalonz"
        mode: "linspace"
        min: 0.5
        max: 5.0
        nvals: 21

      - name: "tauc"
        mode: "linspace"
        min: 0.5
        max: 10.0
        nvals: 21

      - name: "Ts"
        mode: "linspace"
        min: 0.1
        max: 4.1
        nvals: 21

      - name: "As"
        mode: "linspace"
        min: 1.0
        max: 5.0
        nvals: 21

# # # # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  - name: "Database_3"
    description: "(Ln,Phi,Ai,lx,ly,lz,Lz,tc,Ts)"
    base_scenario: "CycloneBaseCase"

    varying_parameters:
      - name: "Ln"
        mode: "linspace"
        min: 0.0
        max: 10.0
        nvals: 21

      - name: "Phi"
        mode: "linspace"
        min: 0.0
        max: 0.06
        nvals: 21

      - name: "Ai"
        mode: "linspace"
        min: 0.0
        max: 1.0
        nvals: 21

      - name: "lambdax"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambday"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambdaz"
        mode: "linspace"
        min: 0.5
        max: 5.0
        nvals: 21

      - name: "lbalonz"
        mode: "linspace"
        min: 0.5
        max: 5.0
        nvals: 21

      - name: "tauc"
        mode: "linspace"
        min: 0.5
        max: 10.0
        nvals: 21

      - name: "Ts"
        mode: "linspace"
        min: 0.1
        max: 4.1
        nvals: 21
# # # # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  - name: "Database_4"
    description: "(Ln,Phi,Ai,lx,ly,lz,Lz,tc)"
    base_scenario: "CycloneBaseCase"

    varying_parameters:
      - name: "Ln"
        mode: "linspace"
        min: 0.0
        max: 10.0
        nvals: 21

      - name: "Phi"
        mode: "linspace"
        min: 0.0
        max: 0.06
        nvals: 21

      - name: "Ai"
        mode: "linspace"
        min: 0.0
        max: 1.0
        nvals: 21

      - name: "lambdax"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambday"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambdaz"
        mode: "linspace"
        min: 0.5
        max: 5.0
        nvals: 21

      - name: "lbalonz"
        mode: "linspace"
        min: 0.5
        max: 5.0
        nvals: 21

      - name: "tauc"
        mode: "linspace"
        min: 0.5
        max: 10.0
        nvals: 21
# # # # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  - name: "Database_5"
    description: "(Ln,Phi,Ai,lx,ly,lz,Lz)"
    base_scenario: "CycloneBaseCase"

    varying_parameters:
      - name: "Ln"
        mode: "linspace"
        min: 0.0
        max: 10.0
        nvals: 21

      - name: "Phi"
        mode: "linspace"
        min: 0.0
        max: 0.06
        nvals: 21

      - name: "Ai"
        mode: "linspace"
        min: 0.0
        max: 1.0
        nvals: 21

      - name: "lambdax"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambday"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambdaz"
        mode: "linspace"
        min: 0.5
        max: 5.0
        nvals: 21

      - name: "lbalonz"
        mode: "linspace"
        min: 0.5
        max: 5.0
        nvals: 21
# # # # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  - name: "Database_6"
    description: "(Ln,Phi,Ai,lx,ly,lz)"
    base_scenario: "CycloneBaseCase"

    varying_parameters:
      - name: "Ln"
        mode: "linspace"
        min: 0.0
        max: 10.0
        nvals: 21

      - name: "Phi"
        mode: "linspace"
        min: 0.0
        max: 0.06
        nvals: 21

      - name: "Ai"
        mode: "linspace"
        min: 0.0
        max: 1.0
        nvals: 21

      - name: "lambdax"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambday"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambdaz"
        mode: "linspace"
        min: 0.5
        max: 5.0
        nvals: 21
# # # # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  - name: "Database_7"
    description: "(Ln,Phi,Ai,lx,ly)"
    base_scenario: "CycloneBaseCase"

    varying_parameters:
      - name: "Ln"
        mode: "linspace"
        min: 0.0
        max: 10.0
        nvals: 21

      - name: "Phi"
        mode: "linspace"
        min: 0.0
        max: 0.06
        nvals: 21

      - name: "Ai"
        mode: "linspace"
        min: 0.0
        max: 1.0
        nvals: 21

      - name: "lambdax"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21

      - name: "lambday"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21
# # # # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  - name: "Database_8"
    description: "(Ln,Phi,Ai,lx)"
    base_scenario: "CycloneBaseCase"

    varying_parameters:
      - name: "Ln"
        mode: "linspace"
        min: 0.0
        max: 10.0
        nvals: 21

      - name: "Phi"
        mode: "linspace"
        min: 0.0
        max: 0.06
        nvals: 21

      - name: "Ai"
        mode: "linspace"
        min: 0.0
        max: 1.0
        nvals: 21

      - name: "lambdax"
        mode: "linspace"
        min: 1.0
        max: 10.0
        nvals: 21
# # # # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  - name: "Database_9"
    description: "(Ln,Phi,Ai)"
    base_scenario: "CycloneBaseCase"

    varying_parameters:
      - name: "Ln"
        mode: "linspace"
        min: 0.0
        max: 10.0
        nvals: 21

      - name: "Phi"
        mode: "linspace"
        min: 0.0
        max: 0.06
        nvals: 21

      - name: "Ai"
        mode: "linspace"
        min: 0.0
        max: 1.0
        nvals: 21
